language: node_js
env:
  - REACT_APP_API_URL=http://localhost:8000/
node_js:
  - "stable"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
after_success:
  - curl -k sftp://s27.mydevil.net/public_html --user ${SFTP_USER}:${SFTP_PASSWORD} -T build --ftp-create-dirs;
notifications:
  email:
    recipients:
      - mail@mateuszjablonski.com
    on_success: change
    on_failure: always
