language: node_js
node_js:
  - "stable"
branches:
  only:
    - master
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
after_success:
  - curl --ftp-create-dirs -T build ftp://s27.mydevil.net/public_html --user ${SFTP_USER}:${SFTP_PASSWORD} \;
notifications:
  email:
    recipients:
      - mail@mateuszjablonski.com
    on_success: change
    on_failure: always
