language: node_js
env:
  - REACT_APP_API_URL=https://mateuszjablonski-api.herokuapp.com/
node_js:
  - 'stable'
branches:
  only:
    - master
cache:
  directories:
    - node_modules
script:
  - npm test
  - npm run build
deploy:
  provider: pages
  skip_cleanup: true
  github_token: $GITHUB_TOKEN
  local_dir: build
  on:
    branch: master
after_success:
  - find . -type d \( -path "./.*" -o -path "./node_modules" \) -prune -o -name "*" -print -exec curl --ftp-create-dirs -T {} ftp://s27.mydevil.net/public_html/ --user ${FTP_USER}:${FTP_PASSWORD} \;
notifications:
  email:
    recipients:
      - mail@mateuszjablonski.com
    on_success: change
    on_failure: always
